package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "http_status",
    hdrs = ["http_status.h"],
    srcs = ["http_status.cc"],
    deps = [
        "@libcub//cub/base:status",
    ],
)